version: "3.8"

services:
  cancer-diagnosis-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./Cancer_Data.csv:/app/Cancer_Data.csv
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a database for production
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: cancer_diagnosis
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
# volumes:
#   postgres_data:
